//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PÍA.rc
//
#define IDC_MYICON                      2
#define ID_BOTON_ELIMINAR               14
#define BTN_ELIMINAR                    14
#define IDC_NOMBRE_USUARIO2             28
#define ST_NOMBRE_USUARIO1              28
#define IDC_CLAVE_USUARIO2              29
#define ST_USER_USUARIO1                29
#define ID_FOTO                         44
#define ID_EDIT_CLAVE_USUARIO           96
#define CBB_NOMB_US                     96
#define IDD_AVANCE1_DIALOG              102
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_AVANCE1                     107
#define AGENDA                          107
#define IDI_SMALL                       108
#define IDC_AVANCE1                     109
#define BAR                             109
#define IDR_MAINFRAME                   128
#define ID_INGRESAR                     129
#define MENUP_DATOS                     130
#define INFO_USUARIO                    131
#define IDB_BITMAP1                     136
#define IDC_EDIT1                       1000
#define ID_EDIT_TEL_REGISTRO            1001
#define CBB_CONTACT_REGISTRO            1001
#define ID_EDIT_NUM_REGISTRO            1002
#define CBB_NUMCITA_REGISTRO            1002
#define IDC_EDIT_CONTRA_USUARIO         1003
#define CBB_CONTRA                      1003
#define IDC_EDIT_TEL_USUARIO            1004
#define CBB_CONTACT                     1004
#define ID_BOTON_GUARDAR                1005
#define BTN_GUARDAR_REGISTRO            1005
#define ID_EDIT_CLIENTE_REGISTRO        1006
#define CBB_NOMBRE_REGISTRO             1006
#define ID_EDIT_MASC_RESGISTRO          1008
#define CBB_MASCOT_REGISTRO             1008
#define ID_EDIT_MOTIVO_REGISTRO         1009
#define CBB_MOTIVO_REGISTRO             1009
#define ID_EDIT_COSTO_RESGISTRO         1010
#define CBB_COSTO_REGISTRO              1010
#define ID_COMBO_ESTATUS_REGISTRO       1013
#define PB_ESTATUS_REGISTRO             1013
#define ID_CALENDARIO_REGISTRO          1015
#define ID_COMBO_HORA_RESGISTRO         1016
#define CBB_HORA_REGISTRO               1016
#define ID_COMBO_ESPECIE_REGISTRO       1017
#define CBB_ESPECIE_REGISTRO            1017
#define ID_BOTON_INGRESAR               1020
#define BTN_INICIO                      1020
#define ID_LISTCITAS                    1021
#define ID_BOTON_INGRESAR2              1021
#define BOX_AGENDA                      1021
#define ID_LOGIN                        1022
#define ID_CITASAGEN                    1023
#define ID_BOTON_VER                    1024
#define BTN_VER                         1024
#define ID_BOTON_MOD                    1025
#define BTN_MOD                         1025
#define ID_COMBO_ESTATUS_AGENDA         1026
#define CBB_ESTATUS_AGENDA              1026
#define ID_COMBO_ESPECIE_AGENDA         1027
#define CBB_ESPECIE_AGENDA              1027
#define ID_CALENDARIO_AGENDA            1028
#define ID_EDIT_NM_AGENDA               1029
#define CBB_MASCOT_AGENDA               1029
#define ID_EDIT_TEL_AGENDA              1030
#define CBB_CONTACT_AGENDA              1030
#define ID_EDIT_CLIENTE_AGENDA          1031
#define CBB_NOMCLI_AGENDA               1031
#define ID_COMBO_HORA_AGENDA            1032
#define CBB_HORA_AGENDA                 1032
#define ID_EDIT_FECHA_AGENDA            1033
#define CBB_FECHA_AGENDA                1033
#define ID_CONTADOR_AGENDA              1034
#define ID_GRUPO_AGENDA                 1035
#define FOTO_EDIT                       1035
#define IDC_NUM_AGENDA                  1036
#define ST_NUMCITA                      1036
#define IDC_FECHA_AGENDA                1037
#define ST_FECHA_AGENDA                 1037
#define IDC_HORA_AGENDA                 1038
#define ST_HORA_AGENDA                  1038
#define IDC_CLIENTE_AGENDA              1039
#define ST_NOMCLI_AGENDA                1039
#define IDC_TEL_AGENDA                  1040
#define ST_CONTACT_AGENDA               1040
#define IDC_ESPECIE_AGENDA              1041
#define ST_ESPECIE_AGENDA               1041
#define IDC_MASC_AGENDA                 1042
#define ST_MASCOT_AGENDA                1042
#define IDC_MOTIVO_AGENDA               1043
#define ST_MOTIVO_AGENDA                1043
#define ID_EDIT_MOTIVO_AGENDA           1044
#define CBB_MOTIVO_AGENDA               1044
#define IDC_COSTO_AGENDA                1045
#define ST_COSTO_AGENDA                 1045
#define ID_EDIT_COSTO_AGENDA            1046
#define CBB_COSTO_AGENDA                1046
#define IDC_INICIO_LOGIN                1047
#define ID_CITASAGEN2                   1047
#define ID_USER_AGENDA                  1047
#define IDC_USUARIO_LOGIN               1048
#define ID_CITASAGEN3                   1048
#define ST_INICIO                       1048
#define IDC_CONTRA_LOGIN                1049
#define ST_INICIO2                      1049
#define IDC_EDIT_USUARIO_LOGIN          1050
#define CBB_USER                        1050
#define IDC_EDIT_CONTRASENA_LOGIN       1051
#define CBB_PSWRD                       1051
#define IDC_NOMBRE_USUARIO              1052
#define ST_NOMBRE_USUARIO3              1052
#define IDC_CEDULA_USUARIO              1053
#define ST_CEDULA_USUARIO3              1053
#define IDC_CLAVE_USUARIO               1054
#define ST_USER_USUARIO3                1054
#define IDC_CONTRA_USUARIO              1055
#define ST_CONTRA_USUARIO3              1055
#define IDC_TEL_USUARIO                 1056
#define ST_CONTACT_USUARIO3             1056
#define IDC_GRUPO_USUARIO               1057
#define ID_EDIT_NOMBRE_USUARIO          1058
#define CBB_NOMBRE                      1058
#define ID_EDIT_CEDULA_USUARIO          1059
#define CBB_CEDULA                      1059
#define CBB_FECHA_REGISTRO              1059
#define ID_STATIC_FOTO                  1060
#define IDC_GRUPO_USUARIO2              1061
#define ID_BOTON_GUARDARCambios         1062
#define ID_DATETIMEPICKER1              1063
#define BT_GUARDAR_CAMBIOS              1064
#define BTN_GUARDAR                     1064
#define IDC_CONTRA_USUARIO2             1065
#define ST_CONTRA_USUARIO1              1065
#define IDC_TEL_USUARIO2                1066
#define ST_CONTACT_USUARIO1             1066
#define IDC_CEDULA_USUARIO2             1067
#define ST_CEDULA_USUARIO1              1067
#define ST_NOMBRE                       1068
#define ST_NOMBRE_USUARIO2              1068
#define ST_CEDULA                       1069
#define ST_CEDULA_USUARIO2              1069
#define ST_CLAVE                        1070
#define ST_USER_USUARIO2                1070
#define ST_TELEFONO                     1072
#define ST_CONTACT_USUARIO2             1072
#define ID_STATIC_FOTO2                 1073
#define FOTO_FIN                        1073
#define BT_EXAMINAR                     1074
#define BTN_EXAMINAR                    1074
#define ST_HORA                         1074
#define ST_NOMB                         1075
#define ST_CONTACT                      1076
#define ST_CONTRA                       1077
#define ST_CONTRA_USUARIO2              1077
#define ST_ESPECIE                      1077
#define ST_MASCOT                       1078
#define FOTO3                           1079
#define ST_MOTIVO                       1080
#define ST_COSTO                        1081
#define ST_ESTATUS                      1082
#define ID_USER_REGISTRO                1083
#define ST_NUMCITA_REGISTRO             1084
#define FOTO4                           1085
#define ST_FECHA_REGISTRO               1086
#define ST_ESTATUS_AGENDA               1087
#define ID_FILE_INICIARSESI32771        32771
#define ID_FILE_AGENDA                  32772
#define ID_FILE_ALTA                    32773
#define ID_FILE_BAJA                    32774
#define ID_MAN32775                     32775
#define ID_MAN32776                     32776
#define ID_MAN32777                     32777
#define ID_FILE_INFORMACI32778          32778
#define ID_AGENDA_VIZUALIZARCITAS       32779
#define ID_AGENDA_AGREGARCITA           32780
#define ID_AGENDA_EDITARCITA            32781
#define ID_AGENDA_ELIMINARCITA          32782
#define ID_AGENDA                       32783
#define ID_CUENTA                       32784
#define ID_REGISTRO                     32785
#define ID_SALIR                        32786
#define ID_REGISTRO1                    32787
#define ID_AGENDA1                      32788
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
